### ISSUE TITLE
The link to the mailling appears to not work (cannot connect)

### ISSUE THREAD

**Issue by crass** [grml/grml.github.com#4]
In the contact section think link to the mailinglist fails to connect (https://ml.grml.org/mailman/listinfo/grml-devel). Does this mean that the mailinglist has been taken down and is no longer a form of developer communication? Or was it moved somewhere else? Or is the server just temporarily down?

**Comment by mika** [comment]
I'm not sure where you found the URL to the https version, but the mailing lists are still available, though http only (for historic reasons), see e.g. http://ml.grml.org/mailman/listinfo/grml

**Comment by zeha** [comment]
@crass our links to ml.grml.org are always using http://. What behaviour were you seeing, when following which link exactly?

**Comment by zeha** [comment]
Fixed the link in d2952b5791b83cf574b6b41563eb384397cb4991
